<?php 
 
// wp-csv-hooks.php
 
namespace Smackcoders\UCI\Core;

if ( ! defined( 'ABSPATH' ) ) {
        die;
}

global $plugin_ajax_hooks;

$plugin_ajax_hooks = [

    'security_performance',
    'settings_options',
    'oneClickUpload',
    'smackuci_check_review_popup',
    'get_options',
    'get_csv_delimiter',
    'support_mail',
    'toolset_state',
    'send_subscribe_email',
    'parse_data',
    'total_records',
    'get_post_types',
    'get_taxonomies',
    'get_authors',
    'get_download',
    'mappingfields',
    'display_log',
    'zip_upload',
    'download_media_log',
    'download_log',
    'download_failed_log',
    'get_desktop',
    'get_ftp_url',
    'get_csv_url',
    'media_mappingfields',
    'get_parse_xml',
    'LineChart',
    'BarChart',
    'displayCSV',
    'updatefields',
    'image_options',
    'delete_image',
    'saveMappedFields',
    'StartImport',
    'GetProgress',
    'ImportState',
    'ImportStop',
    'checkmain_mode',
    'close_notification_action',
    'bulk_file_import',
    'bulk_import',
    'check_export',
    'PauseImport',
    'ResumeImport',
    'active_addons',
    'install_plugins',
    'activate_addon',
    'DeactivateMail',
    'get_ftp_details',
    'delete_log',
    'install_addon',
    'get_setting',
    'get_plugin_notice',
    'dismiss_notice',
    'helperImport',
    'helperSearch',
    'needHelper',
    'wpquery_data',
    // Custom-Fields-Pro hooks
    'database_optimization_process',
    'send_login_credentials_to_users',
    'getfields',
    'templateinfo',
    'search_template',
    'zip_ngg_upload',
    'download_file',
    'download_all_file',
    'delete_file',
    'delete_all_records',
    'delete_all_file',
    'trash_records',
    'display_events',
    'display_schedule',
    'delete_schedule',
    'edit_schedule',
    'update_schedule',
    'displayTemplates',
    'saveTemplate',
    'deleteTemplate',
    'parseDataToScheduleExport',
    'save_schedule_info',
    'timezone',
    'get_server',
    'get_sftp_url',
    'PieChart',
    'checkExtensions',
    'listuploads',
    'locklist',
    'rollback_now',
    'clear_rollback',
    'disable_main_mode',
    'csv_options',
    'send_error_status',
    // Ultimate-Pro hooks
    'delete_dropbox_credentials',
    'delete_gsheet_credentials',
    'get_service_provider',
    'get_bucket_details',
    'get_storage_settings',
    'storage_settings_details',
    'get_total_records',
    'get_category',
    'get_export_fields',
    'DeleteExportTemplate',
    'handle_google_oauth_request',
    'handle_google_oauth_callback',
    'get_post_content',
    'get_image_url',
    'get_test_result',
    'get_export_template',
    'delete_mapping_template_by_hashkey',
    'get_ai_import_context'
];